name: Build MT7621-2

on: 
  release:
    types: [published]
#  push:
#    tags:
#    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: 0 17 * * 4
#  watch:
   # types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        #sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev \
        gcc-multilib
    - name: Clone source code
      run: |
        cd toolchain-mipsel
        mkdir -p toolchain-3.4.x
        wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc.tar.xz
        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: "B70 NEWIFI-D1 GHL K2P-USB-5.0 NEWIFI3 MI-R3G"
      run: |
        cwd=`pwd`
        CONFIG_TOOLCHAIN_DIR=${cwd//\//\\\/}\\/toolchain-mipsel
        cd trunk
        for m in $TNAME;
        do
        if [ ! -f configs/templates/$m.config ] ; then
        echo "configs/templates/$m.config not found "
        exit 1
        fi
        cp -f configs/templates/$m.config .config
        #####################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #É¾³ýÅäÖÃÏîMENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #É¾³ýÅäÖÃÏîSOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #É¾³ýÅäÖÃÏîSOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #É¾³ýÅäÖÃÏîSOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #É¾³ýÅäÖÃÏîSCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #É¾³ýÅäÖÃÏîSS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #É¾³ýÅäÖÃÏîSS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #É¾³ýÅäÖÃÏîDNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #É¾³ýÅäÖÃÏîadbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #É¾³ýÅäÖÃÏîadbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #É¾³ýÅäÖÃÏîadbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #É¾³ýÅäÖÃÏîadbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #É¾³ýÅäÖÃÏî°¢ÀïDDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #ÄÚÍø´©Í¸FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #ÄÚÍø´©Í¸FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config #°¢ÀïDDNS
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> .config #smartdns¶þ½øÖÆÎÄ¼þ
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> .config #v2ray¶þ½øÖÆÎÄ¼þ
        ####################################################################################
        sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}/g" .config
        sudo ./clear_tree_simple
        sudo ./build_firmware_bkye $m
        sudo mv -f images/*.trx /opt/images/
        done
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.R_TOKEN }}
        file: /opt/images/*.trx
        tag: AtuoBuild
        overwrite: true
        file_glob: true
    - uses: ncipollo/release-action@v1
      with:
       bodyFile: "changelog.md"
       tag: AtuoBuild
       allowUpdates: true
       name: Padavan-firmware
       token: ${{ secrets.R_TOKEN }}
